### ISSUE TITLE
Idea: Dragonflies spawning in swampy biomes

### ISSUE THREAD

**Issue by TierraVulture** [EterDelta/CrittersAndCompanions#14]
I absolutely love this mod and I'm excited to see what new features might come next! Til then, here's another idea I've had. Dragonflies spawn in swamps and mangrove swamps. I would configure this myself however I don't think this mod has a config so I thought I'd put this here.

**Comment by EterDelta** [comment]
Forge for 1.19 introduced the biome modifiers, a new way for everyone to control mob spawns through datapacks.
Sadly, because of this, creating a config is no longer possible.

If you wish to know more about how to use biome modifiers, I recommend the following resources:
https://forge.gemwire.uk/wiki/Biome_Modifiers#Add_Spawns
https://github.com/bonsaistudi0s/CrittersAndCompanions/tree/1.19.2/src/generated/resources/data/crittersandcompanions/forge/biome_modifier
