### ISSUE TITLE
Mass spawning of dragonflies gathering at/above world height

### ISSUE THREAD

**Issue by VallenFrostweaver** [EterDelta/CrittersAndCompanions#27]
**Minecraft:** 1.19.2
**Forge:** 43.2.8
**CaC:** 1.1.2

**Issue:** We've been playing on the Cottage Witch modpack on a server and over time we've noticed a large quantity of dragonflies have been gathering at world height. We had 180 at one point which caused me to make this post. It's laggin out our server over time.

**Comment by NiveStinks** [comment]
To add to this, dragonflies seem to want to ascend indefinitely rather than stay low to the ground as they would in real life.

**Comment by EterDelta** [comment]
Thanks for the report. Fixed in version **2.0.2**.

**Comment by WORMSTweaker** [comment]
I would like to reopen this issue because this is **NOT** fixed as of 2.0.2, ~~as seen by this [report](https://o.tas.sh/#r69E)~~ report expired, generated by [Observable](https://www.curseforge.com/minecraft/mc-mods/observable)
Dragonflies are still going extremely high up (231652 blocks in that report), and when loaded, makes the client lag
