### ISSUE TITLE
Critters And Companions breaks Minecolonies in the recent update.

### ISSUE THREAD

**Issue by MidnightMangled** [EterDelta/CrittersAndCompanions#85]
Whenever Critters and Companions is updated to it's most recent update, Minecolonies will break to where you are unable to open their interaction menus with the civilians. Their interaction menus will not pop-up but they'll make a noise, acknowledging you are attempting to interact with them. So, it is likely that Critters and Companions is breaking something in the UI, possibly.

**Comment by OracleMask** [comment]
Had this same issue, had to revert to previous version of Critters and Companions because of it.   Have seen 3 - 4 other people in the Minecolonies discord reporting the same issue as well.

Also, I noticed someone in the CurseForge comments for C&C reporting that this update is also breaking the UI of another mod: Doggy Talents Next.

**Comment by PssbleTrngle** [comment]
Yes, there are some sketchy things happening with entity interaction, I'm on it

**Comment by PssbleTrngle** [comment]
Should be fixed in `2.2.2`, if the issue still exists, feel free to re-open this
